acm_custom_resources:
  custom_policies:
    lambda:
      action:
        - lambda:InvokeFunction
      resource:
        FnSub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-CertificateValidatorCR*
    acm:
      action:
        - acm:*
        - route53:*
      resource: '*'
    opsdns:
      action: 
        - sts:AssumeRole
      resource:
        - Fn::If: 
            - RemoteDNSRecords
            - Ref: CrossAccountDNSZoneIAMRole
            - arn:aws:iam::123456789012:user/noaccess
  roles:
    CertificateValidatorResource:
      policies_inline:
        - cloudwatch-logs
        - acm
        - opsdns
        - lambda
  functions:
    CertificateValidatorCR:
      code: acm_certificate_validator_cr.py
      handler: acm_certificate_validator_cr.handler
      runtime: python3.6
      timeout: 600
      role: CertificateValidatorResource
      environment:
        ENVIRONMENT_NAME:
          Ref: EnvironmentName